apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  namespace: default
  labels:
    run: nginx-1
spec:
  containers:
    - name: nginx-1
      image: registry.iximiuz.com/nginx:alpine
  imagePullSecrets:
    - name: regcred
